[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate --run-syncdb && python manage.py collectstatic --noinput && gunicorn film_scoper.wsgi --bind 0.0.0.0:$PORT --timeout 120"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[build.nixpacksConfig]
pythonVersion = "3.11"