# Generated by Django 5.2.6 on 2025-09-22 04:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('titulo_original', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('año', models.PositiveIntegerField()),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('director', models.CharField(max_length=200)),
                ('reparto', models.TextField(help_text='Actores principales separados por comas')),
                ('sinopsis', models.TextField()),
                ('poster', models.ImageField(blank=True, upload_to='peliculas/posters/')),
                ('banner', models.ImageField(blank=True, upload_to='peliculas/banners/')),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizada', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('calificacion_promedio', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_calificaciones', models.PositiveIntegerField(default=0)),
                ('categorias', models.ManyToManyField(related_name='peliculas', to='core.categoria')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-fecha_agregada'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('foto_perfil', models.ImageField(blank=True, upload_to='usuarios/fotos/')),
                ('biografia', models.TextField(blank=True, max_length=500)),
                ('recibir_notificaciones', models.BooleanField(default=True)),
                ('perfil_publico', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('generos_favoritos', models.ManyToManyField(blank=True, related_name='usuarios_favoritos', to='core.categoria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='ListaVerMasTarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ver_mas_tarde', to=settings.AUTH_USER_MODEL)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_ver_mas_tarde', to='core.pelicula')),
            ],
            options={
                'verbose_name': 'Ver Más Tarde',
                'verbose_name_plural': 'Ver Más Tarde',
                'ordering': ['-fecha_agregada'],
                'unique_together': {('usuario', 'pelicula')},
            },
        ),
        migrations.CreateModel(
            name='ListaFavoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_favoritos', to='core.pelicula')),
            ],
            options={
                'verbose_name': 'Película Favorita',
                'verbose_name_plural': 'Películas Favoritas',
                'ordering': ['-fecha_agregada'],
                'unique_together': {('usuario', 'pelicula')},
            },
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveIntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, max_length=1000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='core.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('usuario', 'pelicula')},
            },
        ),
    ]
