# Generated by Django 5.2.6 on 2025-09-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='peliculas_favoritas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_favoritas', to='core.pelicula'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ver_mas_tarde',
            field=models.ManyToManyField(blank=True, related_name='usuarios_ver_mas_tarde', to='core.pelicula'),
        ),
    ]
