# Generated by Django 5.2.6 on 2025-10-04 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilusuario_peliculas_favoritas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del foro de esta categoría')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foro', to='core.categoria')),
            ],
            options={
                'verbose_name': 'Foro de Categoría',
                'verbose_name_plural': 'Foros de Categorías',
                'ordering': ['categoria__nombre'],
            },
        ),
        migrations.CreateModel(
            name='TemaDeForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('cerrado', models.BooleanField(default=False, help_text='Si está cerrado, no se pueden agregar respuestas')),
                ('destacado', models.BooleanField(default=False, help_text='Temas destacados aparecen primero')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas_creados', to=settings.AUTH_USER_MODEL)),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='core.forocategoria')),
                ('pelicula_relacionada', models.ForeignKey(blank=True, help_text='Película específica de la que trata este tema (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas_foro', to='core.pelicula')),
            ],
            options={
                'verbose_name': 'Tema de Foro',
                'verbose_name_plural': 'Temas de Foro',
                'ordering': ['-destacado', '-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_foro', to=settings.AUTH_USER_MODEL)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.temadeforo')),
            ],
            options={
                'verbose_name': 'Respuesta de Foro',
                'verbose_name_plural': 'Respuestas de Foro',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
