# Generated by Django 5.2.6 on 2025-10-04 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_forocategoria_temadeforo_respuestaforo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Comparte tu opinión sobre esta película', max_length=1000)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.pelicula')),
                ('respuesta_a', models.ForeignKey(blank=True, help_text='Comentario al que responde (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.comentariopelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_peliculas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de Película',
                'verbose_name_plural': 'Comentarios de Películas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['pelicula', '-fecha_creacion'], name='core_coment_pelicul_bd24db_idx'), models.Index(fields=['usuario', '-fecha_creacion'], name='core_coment_usuario_9a377d_idx')],
            },
        ),
    ]
