# Generated by Django 5.2.6 on 2025-10-04 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comentariopelicula'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='calificacion_oficial',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Calificación oficial de fuentes externas (IMDb, Rotten Tomatoes, etc.)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='calificacion_promedio',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Promedio de calificaciones de usuarios de FilmScoper', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
