# Generated by Django 5.2.6 on 2025-10-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_calificacion_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='poster_url',
            field=models.URLField(blank=True, help_text='URL del poster (alternativa al archivo)'),
        ),
    ]
