# Generated by Django 5.2.6 on 2025-10-06 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pelicula_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='tmdb_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Rating de TMDB (sobre 10)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
