# Generated by Django 5.2.6 on 2025-10-06 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pelicula_tmdb_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='tmdb_rating',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='calificacion_oficial',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Calificación oficial de fuentes externas (TMDB, IMDb, Rotten Tomatoes, etc.)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
