# Generated by Django 5.2.6 on 2025-10-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_pelicula_tmdb_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='poster_url',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='poster',
            field=models.URLField(blank=True, help_text='URL del poster desde TMDB'),
        ),
    ]
