# Generated by Django 5.2.6 on 2025-10-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_change_poster_to_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='trailer_youtube_id',
            field=models.CharField(blank=True, help_text='ID del trailer oficial en YouTube (ej: dQw4w9WgXcQ)', max_length=20),
        ),
    ]
